export const QUERY_EXAMPLE = 'QUERY_EXAMPLE';
export const CONTRACT_STORAGE = 'CONTRACT_STORAGE';
export const POST_CONTRACT_STORAGE = 'POST_CONTRACT_STORAGE';

export const SERVICE_STORAGE = 'SERVICE_STORAGE';
export const POST_SERVICE_STORAGE = 'POST_SERVICE_STORAGE';
export const PUT_CONTRACT_STORAGE = 'PUT_CONTRACT_STORAGE';

export const TYPE_SERVICE_STORAGE = 'TYPE_SERVICE_STORAGE';

export const CONTRACT_SERVICE_STORAGE = 'CONTRACT_SERVICE_STORAGE';
export const POST_CONTRACT_SERVICE_STORAGE = 'POST_CONTRACT_SERVICE_STORAGE';

export const PROPERTY_STORAGE = 'PROPERTY_STORAGE';
export const POST_PROPERTY_STORAGE = 'POST_PROPERTY_STORAGE';

export const TYPE_PROPERTY_STORAGE = 'TYPE_PROPERTY_STORAGE';
export const POST_TYPE_PROPERTY_STORAGE = 'POST_TYPE_PROPERTY_STORAGE';